### ISSUE TITLE
This is not an Issue, rather than a question for you <3

### ISSUE THREAD

**Issue by Velosofy** [Mirsario/Terraria-BetterRussian#1]
How did you create those xnb files for the font? I always failed with MonoGame + VS

Thanks :D

**Comment by Mirsario** [comment]
Sorry, forgot to reply. I haven't created the files, someone on the team of the original Russian translation made them, but I don't remember who. I was just asked to make a mod for them, if I remember correctly.
My recommendation is that you just ask around MG's Discord for pointers. Or, y' know, move to FNA. FNA users avoid XNA formats like hell, and just use libraries that import .TTF and other formats.
http://flibitijibibo.com/xnacontent.html
https://github.com/rds1983/FontStashSharp/
